# Generated by Django 5.1.4 on 2025-01-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("homepage", models.URLField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("vote_average", models.FloatField(blank=True, null=True)),
                ("vote_count", models.IntegerField(blank=True, null=True)),
                ("budget", models.BigIntegerField(blank=True, null=True)),
                ("revenue", models.BigIntegerField(blank=True, null=True)),
                (
                    "original_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "languages",
                    models.TextField(
                        blank=True, help_text="Comma-separated languages", null=True
                    ),
                ),
                ("genre_id", models.IntegerField(blank=True, null=True)),
                ("production_company_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
